 name: deploy

 on: [push]

 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - name: executing remote ssh commands using key
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.HOST }}
         port: ${{ secrets.PORT }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.KEY }}
         script: cd ./portfolio_site_gitact; git pull; gulp; cp -r ./dist/* ../gitactiontest/.; rm -rf ./dist
